name: Build RSS
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 6 * * *"  # daily 06:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build feed
        run: python aggregator.py
      - name: Commit feed
        run: |
          git config user.name "netsec-rss-bot"
          git config user.email "actions@users.noreply.github.com"
          git add docs/feed.xml docs/index.html
          git commit -m "Update feed" || echo "No changes"
          git push
